@ECHO OFF
REM === DO NOT EDIT THIS FILE ===
REM You may edit the push-to-nuget.ps1 script to adjust the settings used to upload the package to the NuGet gallery.
SET THIS_SCRIPTS_DIRECTORY=%~dp0
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '%THIS_SCRIPTS_DIRECTORY%push-to-nuget.ps1'"